Repository cantaloupe-project/cantaloupe, pull requests merged in 2024-11, with the labels that each got.

#709 ISSUE-680: proper /MAX handling under pre-cropped and un-cropped scenarios
  src/main/java/edu/illinois/library/cantaloupe/resource/iiif/IIIFResource.java
  src/main/java/edu/illinois/library/cantaloupe/resource/iiif/v2/ImageResource.java
  src/main/java/edu/illinois/library/cantaloupe/resource/iiif/v3/ImageResource.java
  src/test/java/edu/illinois/library/cantaloupe/resource/iiif/ImageResourceTester.java
  src/test/java/edu/illinois/library/cantaloupe/resource/iiif/v2/ImageResourceTest.java
  src/test/java/edu/illinois/library/cantaloupe/resource/iiif/v3/ImageResourceTest.java
Labels: bug, iiif specs implementation

#707 Prevent file handle leak during individual purge
  src/main/java/edu/illinois/library/cantaloupe/cache/FilesystemCache.java
Labels: bug, enhancement

#585 Fix HTTP 302 redirects via delegate for identifiers with slashes
  src/main/java/edu/illinois/library/cantaloupe/image/MetaIdentifier.java
  src/main/java/edu/illinois/library/cantaloupe/resource/AbstractResource.java
  src/main/java/edu/illinois/library/cantaloupe/util/StringUtils.java
  src/test/java/edu/illinois/library/cantaloupe/image/MetaIdentifierTest.java
  src/test/java/edu/illinois/library/cantaloupe/util/StringUtilsTest.java
Labels: checking
